name: docx_template
description: A Docx template engine.
version: 0.3.5
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  archive: ^3.3.0
  # TODO: Update to XML 6.4.2
  xml: ^6.3.0
  # TODO: Update to Collection 1.18.0
  collection: ^1.17.2
  path: ^1.8.2
dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.3
